[package]
name = "svnth"
version = "0.1.0"
authors = ["Sebastian Deutsch <sebastian.deutsch@9elements.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.5"
portaudio = "0.7.0"
